# Generated by Django 4.2.5 on 2023-10-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kicker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="games",
        ),
        migrations.AddField(
            model_name="game",
            name="match",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="kicker.match",
            ),
            preserve_default=False,
        ),
    ]
