# Generated by Django 4.2.5 on 2023-10-09 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kicker", "0002_remove_match_games_game_match"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
